linters-settings:
  lll:
    line-length: 79
    tab-width: 4

  depguard:
    rules:
      "Main":
        files: _test.go # Only apply to go test files.
        allow:
          - $gostd
          - github.com/dancsecs/sztest

  varnamelen:
      ignore-decls:
        - i int
        - mi int
        - ok bool

linters:
  enable-all: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go  # Exclude on test files.
      linters:
        - forbidigo
        - goconst
        - paralleltest
        - wrapcheck

    - path: _internal_test\.go # Exclude on internal test files.
      linters:
        - testpackage

run:
  timeout: 5m
  issues-exit-code: 2
  go: '1.25'
